---
title: "Music Sophistication and Language Sophistication"
author: "Fleetwood Mac Group"
output:
  flexdashboard::flex_dashboard:
    storyboard: true
    theme: sandstone
    orientation: columns
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(ggplot2)
library(plotly)
library(plyr)
library(flexdashboard)

# Make some noisily increasing data
set.seed(955)
dat <- data.frame(cond = rep(c("A", "B"), each=10),
                  xvar = 1:20 + rnorm(20,sd=3),
                  yvar = 1:20 + rnorm(20,sd=3))

df_results = read.csv("survey_results_for_analysis_11012024.csv")

library(dplyr)

df_results <- df_results %>%
  mutate(Language = gsub(" ", "", toupper(Language)))
```

Sidebar {.sidebar}
=====================================

```{r}
print ("Here we have some basic information about the project")
```

Main page
=======================================================================


Column {data-width=600}
-----------------------------------------------------------------------

### Selecting the English proficiency groups {data-height=100}

Here you will be able to filter the data on the chart by the english proficiency. 

```{r}

 
```

### Our main chart, displaying the main findings {data-height=900}

```{r}
 plot_title <- paste("Scatter plot for", " sentiment")
  
  # Create the scatter plot
  p <- ggplot(df_results, aes(x = SC0, y = sentiment_mean, shape =as.factor(English.proficiency), color=Language )) +
    geom_point() +
    ggtitle(plot_title)
  
  # Print or save the plot (you can customize this based on your needs)
  ggplotly(p)
```



Column {data-width=400}
-----------------------------------------------------------------------

### Bar chart with data per English proficiency

```{r}
print ("Here we'll have another interesting graph")
```

### Data Table

```{r}
print ("Here we'll have some raw data")
```

Background
=======================================================================


Column
-----------------------------------------------------------------------

### Introduction

```{r}
print ("General introduction")
```

### Methodology

```{r}
print ("Detailing the process of the experiment")
```

### Conclusions

```{r}
print ("here we'll have conclusions")
```


Row
-----------------------------------------------------------------------

### Some source material

```{r}

```



More Graphs
=======================================================================
Column {data-width=800}
-----------------------------------------------------------------------

### Selecting the variables {data-height=200}

```{r}
print ("this will enable you to select what data to display on the graph")
```

### Custom chart {data-height=800}

```{r}
print ("this section will include a customizable graph")
```



Column {data-width=200}
-----------------------------------------------------------------------


### Relevant data table

```{r}

```